# Generated by Django 5.2.16 on 2026-09-20 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowLend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Returned', 'Returned')], default='Pending', max_length=16)),
                ('type', models.CharField(choices=[('borrow', 'Borrow'), ('lend', 'Lend')], max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_lend_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
