# Generated by Django 6.0.2 on 2026-02-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "loan_type",
                    models.CharField(
                        choices=[("BORROW", "Borrow"), ("LEND", "Lend")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
