# Generated by Django 6.0.2 on 2026-03-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="interest_period",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                    ("MONTHLY", "Monthly"),
                    ("YEARLY", "Yearly"),
                ],
                default="YEARLY",
                max_length=10,
            ),
        ),
    ]
